# Funding options for My project
# This project is 100% free and open source!
# If you'd like to support development, consider:

github: # Johnshah
patreon: # Add your patreon username here
ko_fi: # Add your ko-fi username here
custom: # Add custom sponsorship URL
