version: '3.8'
services:
  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
  backend:
    image: python:3.11
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
  ai-engine:
    image: ubuntu:22.04
    working_dir: /app
    volumes:
      - ./ai_engine:/app
    # models and runtimes must be configured by the user locally
